baseurl = "https://arjunsehajpal.com/"
title = "Arjun's Blog"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
canonifyUrls = true

[pagination]
  pagerSize = 20

[markup]
	[markup.highlight]
		codeFences = true
		style = "bw"
		guessSyntax = false
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    author = "Arjun Sehajpal"
    info = "Learning to make Machine Learning work in real world"
    description = "A blog about Data Science and Machine Learning"
    keywords = "blog, data science, machine learning, data engineering"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Tech, tips and stuff"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    colorScheme = "dark"
    customCSS = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/arjunsehajpal/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/arjunsehajpal/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
